### PR TITLE
Use pathlib for path handling

### LINKED ISSUE #39: Convert to using Pathlib
All of the path handling is done using strings and `os.path` this is prone to issues with running on different operating systems. Best practise for path-handling in Python is to use the inbuilt `pathlib` module.

### PR DESCRIPTION
**Pull request by tsmbland**
This PR aims to make full use of the inbuilt `pathlib` module to handle paths, which were previously being passed around as strings. Mostly this is to ensure compatibility on different operating systems, but the syntax is also tidier and makes the code a bit more readable.

The tests pass locally, although the testing suite is minimal, so I'm sure someone will want to try this out more thoroughly before merging

Close #39

### CODE REVIEW

**Comment by alexdewar** [comment]
Thanks for this @tsmbland!

The only problem is that this PR and your other one are likely to cause merge conflicts with @Thomas-Rowlands' mega-PR (#20). We've got a meeting with the team today, so hopefully we'll be able to figure out a strategy to get all the PRs merged together.

With your `pre-commit` PR, were a lot of manual fixes required or were they mostly automated? I'm just wondering how much work it would be to re-fix things after merging #20.

**Comment by alexdewar** [comment]
Yeah, sorry I didn't make it clear in the issue descriptions :disappointed:. Hopefully we should just be able to merge it with your work.

**Review by Thomas-Rowlands — APPROVED** [review]
Tested and looks good :)

**Comment by alexdewar** [comment]
@Thomas-Rowlands There are now a bunch of merge conflicts with #20. See my comments above

**Comment by Thomas-Rowlands** [comment]
Indeed, #20 is very old at this point and has such a large amount of changes I would expect nothing less. Unfortunately as #20 also contains intended changes to the way table processing is handled, for example, I'm not certain the regression test would be a guarantee of success. #20 will need to be picked through with a fine-toothed comb after merging locally, so this may take a while.

Speak shortly in the Teams meeting.

**Comment by alexdewar** [comment]
Okey doke. Speak soon then.

**Pull request merged**
