### PR TITLE
Include data files in package

### LINKED ISSUE #32: Make repo package-able
The repo structure is not currently consistent with the tooling used for building python packages. In particular, the data files are not in findable locations.

Ideally we should lift the severity of restrictions on dependencies for compatibility with other people's code.

Some requirements for this:
- [x] #72
- [x] Might need to restructure the source code directory (src vs module name alone?)
- [x] Consolidate the data/config files into the package and make poetry aware of them.
- [x] Need to include data files with `importlib` (specifically in `utils.py`)
- [x] #71

### PR DESCRIPTION
**Pull request by AdrianDAlessandro**
# Description

This makes it possible to run `auto-corpus` from any directory on the computer it is installed on by by getting the path for the required data files from the `importlib.resources` module.

I have not included the `configs`, `keyFiles`, and `trainedData` directories in the repo because they appear to be unused in the package itself and only used as additional inputs that can be configured via the command line arguments.

Since this is finalising the steps to make the repo package able, I have included some package metadata and updated the version number to v1.1.0 (I chose this over 1.0.1 because of the change to the main interface from removing `run_app.py`)

Fixes #32 

## Type of change

- [x] Documentation (non-breaking change that adds or improves the documentation)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [x] All tests pass (eg. `pytest`)
- [x] The documentation builds and looks OK (eg. `mkdocs`)
- [x] Pre-commit hooks run successfully (eg. `pre-commit run --all-files`)

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added or an issue has been opened to tackle that in the future. (Indicate issue here: # (issue))

### CODE REVIEW

**Comment by alexdewar** [comment]
This actually needs some tweaks because it won't work as is. In general, it's better to just add an approving review rather than just merge straight away. Then let the author can merge it once they've made any necessary changes and others have reviewed it.

Not a problem though. It won't actually break things as is, but there are other changes that will need doing at some point. I'll add a review anyway and maybe we can open an issue or two for remaining bits. We're actually out of time to work on this project now, so I don't think we'll get a chance to wrap it up ourselves, unfortunately.

**Comment by Thomas-Rowlands** [comment]
Apologies Alex, assumed as it wasn't a draft and my review was requested it was ready to do a test run and merge

**Review by alexdewar — COMMENTED** [review]
So this is a better approach in general and *partially* fixes the problem, but unfortunately the data files will still not be included in the wheel when you build it, so this won't work when downloaded from PyPI. Poetry (and I think other Python build tools) will ignore any non-Python files, so you need to list them separately in your `pyproject.toml`. For poetry you do it like this: https://python-poetry.org/docs/pyproject#include-and-exclude

There are also some other data files lurking around in the repo which aren't under `src/` at all:

- `configs` -- bundling these will also require some code changes, as currently you have to supply the path to these files
- `trainedData` -- I *think* these are used by the OCR code

I can open issues for these things.

**Comment by alexdewar** [comment]
> Apologies Alex, assumed as it wasn't a draft and my review was requested it was ready to do a test run and merge

No worries!

**Comment by AdrianDAlessandro** [comment]
> So this is a better approach in general and _partially_ fixes the problem, but unfortunately the data files will still not be included in the wheel when you build it, so this won't work when downloaded from PyPI. Poetry (and I think other Python build tools) will ignore any non-Python files, so you need to list them separately in your `pyproject.toml`. For poetry you do it like this: https://python-poetry.org/docs/pyproject#include-and-exclude

I thought I would need to do this but turns out it's not needed. I read that Poetry automatically includes all files in the package directory (can't remember where, somewhere in the poetry docs). I ran `poetry build` and unpacked the tarball and it had all the non-python files inside the `autocorpus` directory.

> There are also some other data files lurking around in the repo which aren't under `src/` at all:
> 
> * `configs` -- bundling these will also require some code changes, as currently you have to supply the path to these files
> * `trainedData` -- I _think_ these are used by the OCR code

I couldn't find any references to these files inside the code, and they're both provided as command line arguments, so the user needs to know the path to these files. I think there's an argument for changing this design, but it requires a bigger change to the code that felt out of scope for this PR

**Comment by alexdewar** [comment]
> I thought I would need to do this but turns out it's not needed. I read that Poetry automatically includes all files in the package directory (can't remember where, somewhere in the poetry docs). I ran `poetry build` and unpacked the tarball and it had all the non-python files inside the `autocorpus` directory.

Oh, my bad! I just tried it and you're totally right.

> I couldn't find any references to these files inside the code, and they're both provided as command line arguments, so the user needs to know the path to these files. I think there's an argument for changing this design, but it requires a bigger change to the code that felt out of scope for this PR

I didn't realise they're not called from the code directly. You're right they should be in different PRs anyway.

I'll open issues for them anyway because it probably would be useful for end-users if they had these files included with their `pip install` (in some form).

**Pull request merged**
