### PR TITLE
Migrate from `setup.py` to `pyproject.toml` and `poetry`

### LINKED ISSUE #24: Change from setup.py to pyproject.toml
This is the more modern way to specify dependencies etc.

We should use `poetry` as a backend (though others are available).

### PR DESCRIPTION
**Pull request by alexdewar**
This PR migrates the dependency management from using `setup.py` + `requirements.txt` (which is deprecated), to [`poetry`](https://python-poetry.org/), a modern tool which can also handle managing virtual environments and upgrading dependencies etc.

As far as possible, I tried to keep the versions of direct dependencies the same as they currently are in `requirements.txt`, even though these are out of date (#35), in case newer versions break things. The plan is still to upgrade the dependencies, once we have verified that this doesn't break anything (hopefully with some regression tests). With `poetry`, you only need to specify direct dependencies in `pyproject.toml` and the versions of indirect dependencies are specified in the auto-generated lock file, so some of these packages will be newer versions, though this shouldn't matter.

There are some caveats:

- I had to upgrade `opencv-contrib-python`, because the version specified in `requirements.txt` wouldn't build for me. The major version is still the same, so there shouldn't be compatibility problems.
- I had to upgrade `lxml`, because the version in `requirements.txt` wouldn't build for me on Windows. This involved a major version bump (v4 to v5), so it is *possible* that this could break things (although I looked at [the changelog](https://lxml.de/changes-5.1.0.html) and didn't see anything worrying). Please check that I haven't broken anything here!
- I've had to add some *indirect* dependencies to `pyproject.toml`, because the versions `poetry` selected by default broke things (one package had been yanked and numpy v2 didn't work with the older version of `networkx`). We should be able to remove these entries once we've upgraded all the other dependencies.

I tested that the virtualenv created by poetry worked on both Linux and Windows (using Python v3.10) with the example PMC file that @jmp111 sent and produced the same output as with the old `requirements.txt` file.

I was going to update the README file to include instructions on how to get started with `poetry`, but as there are some other things I want to change in there, I'll hold off for now.

To install `poetry`, follow these instructions: https://python-poetry.org/docs/#installing-with-pipx

Closes #24.

### CODE REVIEW

**Comment by Thomas-Rowlands** [comment]
Testing on Windows 11 with Python 3.10, the poetry install command using the provided .lock file throws the error:
```
The lock file does not have a metadata entry.
Regenerate the lock file with the 'poetry lock' command.
```

**Comment by alexdewar** [comment]
Hmm... that's strange. I just tried with Windows 10 + Python 3.10 and it worked for me.

How did you install `poetry` and what version is it?

**Comment by Thomas-Rowlands** [comment]
False alarm, the lock file was cut off part way, re-copied it across and it installs. Testing now but as its just dependencies installing, rather than AC code changes, I imagine it will be fine

**Review by Thomas-Rowlands — APPROVED** [review]
Tested and runs through as expected

**Comment by alexdewar** [comment]
Great! Thank you for testing.

**Pull request merged**
